[project]
title="Librem5 Motherboard"
company="Purism"
revision="C.1.X"

[jig]
orientation = 90
probe_side = "bottom"
probe_class = "R100"

[jig.probe_board]
orientation = 90

[jig.layers]
pressure_pin.file = "librem5_mainboard-pressure_pins.gbr"
outline.file = "librem5_mainboard-Edge_Cuts.gm1"
clearance.file = "librem5_mainboard-clearance.gbr"
clearance.height = 5
support.file = "librem5_mainboard-support.gbr"
support.height = 4
probe.file = "librem5_mainboard-probe.gbr"
probe.height = 10
base.file = "librem5_mainboard-base.gbr"
base.height = 10

[jig.probes]
gnd_height=-4
