[project]
title="Glasgow"
company="Glasgow Embedded"
revision="C.1.X"

[jig]
orientation = 90
probe_side = "bottom"
probe_class = "R100"

[jig.probe_board]
orientation = 90

[jig.layers]
pressure_pin.file = "pressure_pins.gbr"
outline.file = "glasgow-Edge_Cuts.gm1"
clearance.file = "glasgow-clearance.gbr"
clearance.height = 5
support.file = "glasgow-support.gbr"
support.height = 4
probe.file = "glasgow-probe.gbr"
probe.height = 10
base.file = "glasgow-base.gbr"
base.height = 10

[jig.probes]
gnd_height=-4
